export const actionTypes = {
  ASSIGN_PROCESSES: 'ASSIGN_PROCESSES',
  ASSIGN_PROJECTS: 'ASSIGN_PROJECTS',
  ASSIGN_STDOUT: 'ASSIGN_STDOUT',
  ASSIGN_STDERR: 'ASSIGN_STDERR',
  ASSIGN_ERRORS: 'ASSIGN_ERRORS',
  SELECT_PROCESS: 'SELECT_PROCESS',
  SELECT_TAB: 'SELECT_TAB'
}
