module.exports = {
  PROCESSES_CHANNEL: 'PROCESSES_CHANNEL',
  GENERAL_CHANNEL: 'GENERAL_CHANNEL',
  GENERAL_ERROR: 'GENERAL_ERROR',
  GET_PROJECTS: 'GET_PROJECTS',
  PROJECTS_LIST: 'PROJECTS_LIST',
  START_PROCESS: 'START_PROCESS',
  PROCESSES_LIST: 'PROCESSES_LIST',
  PROCESS_STARTED: 'PROCESS_STARTED',
  PROCESS_FINISHED: 'PROCESS_FINISHED',
  STDOUT: 'STDOUT',
  STDERR: 'STDERR'
}
